### ISSUE TITLE
Feature request: Input results from guess

### ISSUE THREAD

**Issue by hrdwdmrbl** [ttop/wordle_starting_guess#2]
**Note: Contains spoiler's for today**

Today I built a super crude guess suggester to suggest me some second guesses after giving it the results of my first guess. Really there is no point in blindly doing a second guess if the first guess already gave feedback.

So my request is to incorporate (and document!) some command line arguments to input results

For example, after guessing "bacon" and being told that the word contains an o at position 3, contains a b somewhere and does not contain a, c or n

`python wordle.py 3=o contains=b notcontains=acn`

then it would spit out and rank the 

robot
elbow
throb

**Comment by ttop** [comment]
I really wish you hadn't included a spoiler for today's – my eyes were immediately drawn to the command line example rather than your disclaimer. Ultimately the answer was the one word stuck in my head after I finally saw your "spoiler" message.

**Comment by ttop** [comment]
I'm not trying to build a tool to help a human solve a specific puzzle (that's just cheating, in my opinion, and takes the fun and real brain work out of solving the puzzles), so this is not a feature I will be implementing. What I've been working on are tools to help determine the best strategy to use. For a follow-up project I have already written solver code that narrows down the word list to just eligible words based on the guess responses, but it is in the service of trying to determine the best guessing strategy.
